apiVersion: v1
kind: ServiceAccount
metadata:
  name: aeroscale-worker-sa
  namespace: aeroscale
  annotations:
    iam.gke.io/gcp-service-account: aeroscale-worker@stayrelevantid.iam.gserviceaccount.com